name: Push code in dev branch to Test PyPI on merge

on:
  pull_request:
    branches: [ development ]
    types: [closed]

jobs:
  push-dev-code-to-test-pypi:
    name: Push development branch to test PyPI
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
       - name: Check-out development branch
         uses: actions/checkout@v2
         with:
           ref: 'development'
       - name: Setup Python
         uses: actions/setup-python@v1
         with:
           python-version: 3.7
       - name: Update pip
         run: python -m pip install --user --upgrade pip
       - name: Install pypa/build
         run: >-
           python -m
           pip install
           build
           --user
       - name: Build a binary wheel and a source tarball
         run: >-
           python -m
           build
           --sdist
           --wheel
           --outdir dist/
           .
       - name: Publish distribution to Test PyPI
         uses: pypa/gh-action-pypi-publish@master
         with:
           user: __token__
           password: ${{ secrets.test_pypi_password }}
           repository_url: https://test.pypi.org/legacy/
