name: SimpleOR continuous integration

on:
    pull_request:
        branches: [ master ]

jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ 3.7, 3.8 ]
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python }}
            - name: Install Tox and any other packages
              run: pip install tox
            - name: Print current working directory and files
              run: pwd
            - name: print files
              run: |
                /bin/bash
                ls -la
            - name: Run tox
              run: tox -e py
