name: SimpleOR continuous integration

on:
    pull_request:
        branches: [ master ]

jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 2
            matrix:
                python-version: [ 3.7, 3.8 ]
        steps:
            - uses: actions/checkout@v1
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python }}
            - name: Install Tox and any other packages
              run: |
                  python -m pip install --upgrade pip
                  pip install tox tox-gh-actions
            - name: Run tox
              run: tox
