name: Tests on development branch

on:
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8]

    steps:
      - name: Check-out development branch
        uses: actions/checkout@v2
        with:
          ref: 'development'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
#      - name: Install Tox and any other packages
#        run: |
#          pip install --upgrade pip
#          pip install tox
#      - name: Run Tox
#        uses: actions/checkout@v2
#          # Run tox using the version of Python in `PATH`
#        run: tox -e py
